# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: [push]
  

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{matrix.os_version}}
    strategy:
      matrix:
        py_version: ["3.9", "3.10"]
        os_version: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{matrix.py_version}}
      uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.py_version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python3 -m pip install --upgrade build
        python -m pip install --upgrade pip setuptools wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build
      run: |
        python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/COS397-assignment6

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: "pypi-AgENdGVzdC5weXBpLm9yZwIkMzRmZDFjNjYtNjhhMC00OGJkLWFkMzUtMmE5ZTg4Y2I0YzMwAAIqWzMsImM1NWY1NGQxLWFjODktNGEzYi1iYjA4LTZkNzM0OGI2NWNlNiJdAAAGIMolO90lqIflGnAK_AYdUM0WHd2Q9JMMWobl1ZDahf9X"
        repository-url: https://test.pypi.org/legacy/
